In [10]:
df = pd.read_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_data_raw.csv")
df.head()

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
0,1000001,Swiggy Instamart,Noida,46,702.33750,19.182,11.97,12.0,Dairy,Wallet,2.1,1,3.2
1,1000002,Flipkart Minutes,Amritsar,56,1007.30000,19.644,12.74,10.0,Snacks,Cash on Delivery,2.3,0,3.2
2,1000003,Flipkart Minutes,Mumbai,18,1211.66000,16.910,4.85,NaN,Personal Care,Cash on Delivery,3.3,0,3.8
3,1000004,Swiggy Instamart,Delhi,23,1179.05925,5.864,6.44,2.0,Dairy,Credit Card,5.0,1,5.0
4,1000005,Dunzo,Mumbai,44,586.02550,12.470,2.45,13.0,Household,Wallet,3.7,0,4.8

In [11]:
df['Items_Count'].isnull().sum()

35000

In [12]:
df.shape

(1000000, 13)

In [13]:
df['Items_Count'] = df['Items_Count'].fillna(df['Items_Count'].median())

In [14]:
df['Items_Count'].isnull().sum()

0

In [15]:
df.duplicated().sum()

0

In [16]:
df.dtypes

Order_ID                     int64
Company                     object
City                        object
Customer_Age                 int64
Order_Value                float64
Delivery_Time_Min          float64
Distance_Km                float64
Items_Count                float64
Product_Category            object
Payment_Method              object
Customer_Rating            float64
Discount_Applied             int64
Delivery_Partner_Rating    float64
dtype: object

In [17]:
df['SLA_Breach'] = df['Delivery_Time_Min'] > 10

In [18]:
df['SLA_Breach'].value_counts()

SLA_Breach
True     848776
False    151224
Name: count, dtype: int64

In [19]:
df.groupby('City')['SLA_Breach'].mean().sort_values(ascending=False)

City
Haridwar     1.000000
Jaipur       0.981546
Mumbai       0.936405
Bengluru     0.913857
Amritsar     0.883059
Pune         0.882693
Gurgaon      0.881993
Kolkata      0.881413
Hyderabad    0.881406
Chennai      0.880368
Noida        0.878774
Delhi        0.164467
Name: SLA_Breach, dtype: float64

In [20]:
df.groupby('SLA_Breach')['Distance_Km'].mean()

SLA_Breach
False    5.784701
True     8.100424
Name: Distance_Km, dtype: float64

In [23]:
df['Distance_Bucket'] = pd.cut(df['Distance_Km'], bins=[0,2,4,6,8,10,15,20,50])
df.groupby('Distance_Bucket')['SLA_Breach'].mean()

C:\Users\Admin\AppData\Local\Temp\ipykernel_15560\2843924811.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Distance_Bucket')['SLA_Breach'].mean()

Distance_Bucket
(0, 2]      0.708132
(2, 4]      0.779093
(4, 6]      0.821122
(6, 8]      0.840673
(8, 10]     0.865893
(10, 15]    0.926528
(15, 20]         NaN
(20, 50]         NaN
Name: SLA_Breach, dtype: float64

In [24]:
df.groupby('Distance_Bucket')['Delivery_Time_Min'].mean()

C:\Users\Admin\AppData\Local\Temp\ipykernel_15560\151689593.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Distance_Bucket')['Delivery_Time_Min'].mean()

Distance_Bucket
(0, 2]      12.755054
(2, 4]      13.737503
(4, 6]      14.822424
(6, 8]      15.987545
(8, 10]     17.157555
(10, 15]    19.211455
(15, 20]          NaN
(20, 50]          NaN
Name: Delivery_Time_Min, dtype: float64

In [25]:
df.groupby('Company')['SLA_Breach'].mean().sort_values(ascending=False)

Company
Jio Mart            0.980422
Amazon Now          0.943060
Big Basket          0.935399
Flipkart Minutes    0.926447
Swiggy Instamart    0.911700
Blinkit             0.878196
Dunzo               0.824428
Zepto               0.391115
Name: SLA_Breach, dtype: float64

In [26]:
df.groupby('Company')['Distance_Km'].mean().sort_values()

Company
Zepto               7.735675
Amazon Now          7.744768
Jio Mart            7.748125
Big Basket          7.748827
Blinkit             7.749559
Swiggy Instamart    7.752138
Dunzo               7.752200
Flipkart Minutes    7.770453
Name: Distance_Km, dtype: float64

In [27]:
df.groupby('Company')['Delivery_Time_Min'].mean().sort_values()

Company
Zepto                9.570524
Dunzo               14.119290
Blinkit             15.066593
Swiggy Instamart    16.019186
Flipkart Minutes    16.991363
Big Basket          17.980340
Amazon Now          18.940342
Jio Mart            22.961049
Name: Delivery_Time_Min, dtype: float64

In [28]:
df.to_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv", index=False)

In [30]:
city_summary = df.groupby('City').agg(
    Total_Orders=('Order_ID','count'),
    Breach_Rate=('SLA_Breach','mean'),
    Avg_Distance=('Distance_Km','mean'),
    Avg_Delivery_Time=('Delivery_Time_Min','mean')
).sort_values('Breach_Rate', ascending=False)

city_summary

           Total_Orders  Breach_Rate  Avg_Distance  Avg_Delivery_Time
City
Haridwar          78958     1.000000      7.771147          27.541573
Jaipur            78901     0.981546      7.759775          20.549048
Mumbai            79078     0.936405      7.737168          17.511957
Bengluru          78973     0.913857      7.746353          16.515318
Amritsar          79074     0.883059      7.780874          15.568514
Pune              78580     0.882693      7.769871          15.558817
Gurgaon           79004     0.881993      7.746602          15.553255
Kolkata           79174     0.881413      7.752189          15.534904
Hyderabad         79481     0.881406      7.728064          15.533696
Chennai           78725     0.880368      7.744297          15.534581
Noida             78869     0.878774      7.733520          15.512747
Delhi             79183     0.164467      7.730374           7.139339

In [31]:
city_summary[['Total_Orders','Breach_Rate']].sort_values('Total_Orders', ascending=False)

           Total_Orders  Breach_Rate
City
Hyderabad         79481     0.881406
Delhi             79183     0.164467
Kolkata           79174     0.881413
Mumbai            79078     0.936405
Amritsar          79074     0.883059
Gurgaon           79004     0.881993
Bengluru          78973     0.913857
Haridwar          78958     1.000000
Jaipur            78901     0.981546
Noida             78869     0.878774
Chennai           78725     0.880368
Pune              78580     0.882693

In [32]:
df.groupby(['City','Company'])['SLA_Breach'].mean().loc['Delhi'].sort_values()

Company
Blinkit             0.000000
Dunzo               0.000000
Zepto               0.000000
Swiggy Instamart    0.026892
Flipkart Minutes    0.084836
Big Basket          0.176380
Amazon Now          0.284548
Jio Mart            0.750740
Name: SLA_Breach, dtype: float64

In [33]:
df.groupby(['City'])['SLA_Breach'].mean()  # already have this
df[df['Company']=='Jio Mart'].groupby('City')['SLA_Breach'].mean().sort_values()

City
Delhi        0.75074
Amritsar     1.00000
Bengluru     1.00000
Chennai      1.00000
Gurgaon      1.00000
Haridwar     1.00000
Hyderabad    1.00000
Jaipur       1.00000
Kolkata      1.00000
Mumbai       1.00000
Noida        1.00000
Pune         1.00000
Name: SLA_Breach, dtype: float64

In [34]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

df_model = df[['City','Company','Distance_Km','Delivery_Time_Min','SLA_Breach']].copy()

le_city = LabelEncoder()
le_company = LabelEncoder()
df_model['City_enc'] = le_city.fit_transform(df_model['City'])
df_model['Company_enc'] = le_company.fit_transform(df_model['Company'])

X = df_model[['City_enc','Company_enc','Distance_Km']]
y = df_model['SLA_Breach']

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

importance = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)
importance

City_enc       0.468364
Company_enc    0.369921
Distance_Km    0.161715
dtype: float64

In [35]:
df.groupby('Product_Category')['SLA_Breach'].mean().sort_values(ascending=False)

Product_Category
Household              0.850275
Groceries              0.849625
Fruits & Vegetables    0.849132
Beverages              0.848734
Personal Care          0.848513
Snacks                 0.848051
Dairy                  0.847112
Name: SLA_Breach, dtype: float64

In [36]:
df.groupby('SLA_Breach')['Order_Value'].mean()

SLA_Breach
False    612.182395
True     564.420899
Name: Order_Value, dtype: float64

In [37]:
df.to_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv", index=False)

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv")

In [3]:
city_avg = df.groupby('City')['Delivery_Time_Min'].mean().reset_index()
city_avg.columns = ['City', 'City_Avg_Delivery_Time']
df = df.merge(city_avg, on='City', how='left')
df['Above_City_Avg'] = df['Delivery_Time_Min'] > df['City_Avg_Delivery_Time']
df.head()

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating,SLA_Breach,Distance_Bucket,City_Avg_Delivery_Time,Above_City_Avg
0,1000001,Swiggy Instamart,Noida,46,702.33750,19.182,11.97,12.0,Dairy,Wallet,2.1,1,3.2,True,"(10, 15]",15.512747,True
1,1000002,Flipkart Minutes,Amritsar,56,1007.30000,19.644,12.74,10.0,Snacks,Cash on Delivery,2.3,0,3.2,True,"(10, 15]",15.568514,True
2,1000003,Flipkart Minutes,Mumbai,18,1211.66000,16.910,4.85,10.0,Personal Care,Cash on Delivery,3.3,0,3.8,True,"(4, 6]",17.511957,False
3,1000004,Swiggy Instamart,Delhi,23,1179.05925,5.864,6.44,2.0,Dairy,Credit Card,5.0,1,5.0,False,"(6, 8]",7.139339,False
4,1000005,Dunzo,Mumbai,44,586.02550,12.470,2.45,13.0,Household,Wallet,3.7,0,4.8,True,"(2, 4]",17.511957,False

In [7]:
df.to_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv", index=False)

In [8]:
df.columns.tolist()

['Order_ID',
 'Company',
 'City',
 'Customer_Age',
 'Order_Value',
 'Delivery_Time_Min',
 'Distance_Km',
 'Items_Count',
 'Product_Category',
 'Payment_Method',
 'Customer_Rating',
 'Discount_Applied',
 'Delivery_Partner_Rating',
 'SLA_Breach',
 'Distance_Bucket',
 'City_Avg_Delivery_Time_x',
 'Above_City_Avg',
 'City_Avg_Delivery_Time_y']

In [9]:
df.to_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv", index=False)

In [10]:
df.to_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv", index=False)
print("Saved:", df.shape)

Saved: (1000000, 18)

In [11]:
df.columns.tolist()

['Order_ID',
 'Company',
 'City',
 'Customer_Age',
 'Order_Value',
 'Delivery_Time_Min',
 'Distance_Km',
 'Items_Count',
 'Product_Category',
 'Payment_Method',
 'Customer_Rating',
 'Discount_Applied',
 'Delivery_Partner_Rating',
 'SLA_Breach',
 'Distance_Bucket',
 'City_Avg_Delivery_Time_x',
 'Above_City_Avg',
 'City_Avg_Delivery_Time_y']

In [12]:
df = df.drop(columns=['City_Avg_Delivery_Time_x'])
df = df.rename(columns={'City_Avg_Delivery_Time_y': 'City_Avg_Delivery_Time'})
df.columns.tolist()

['Order_ID',
 'Company',
 'City',
 'Customer_Age',
 'Order_Value',
 'Delivery_Time_Min',
 'Distance_Km',
 'Items_Count',
 'Product_Category',
 'Payment_Method',
 'Customer_Rating',
 'Discount_Applied',
 'Delivery_Partner_Rating',
 'SLA_Breach',
 'Distance_Bucket',
 'Above_City_Avg',
 'City_Avg_Delivery_Time']

In [13]:
df.to_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv", index=False)
print("Done:", df.shape)

Done: (1000000, 17)

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv")
df['Distance_Bucket'].value_counts()

Distance_Bucket
(10, 15]    344293
(4, 6]      138424
(8, 10]     137935
(6, 8]      137874
(2, 4]      137773
(0, 2]      103701
Name: count, dtype: int64

In [3]:
df['Distance_Bucket'] = pd.cut(df['Distance_Km'], 
    bins=[0,2,4,6,8,10,15,20,50],
    labels=['0-2 km','2-4 km','4-6 km','6-8 km','8-10 km','10-15 km','15-20 km','20+ km'])

df.to_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv", index=False)
print("Done")

Done

NameError: name 'df' is not defined

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv")
df['Distance_Bucket'].value_counts()

Distance_Bucket
10-15 km    344293
4-6 km      138424
8-10 km     137935
6-8 km      137874
2-4 km      137773
0-2 km      103701
Name: count, dtype: int64

In [3]:
df['SLA_Breach'] = df['SLA_Breach'].astype(int)
df.to_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv", index=False)

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv")
df = df.dropna(subset=['City'])
df.to_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv", index=False)
print(df.shape)

(948000, 17)

In [3]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv")
df['SLA_Breach_Pct'] = df['SLA_Breach'] * 100
df.to_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv", index=False)

In [4]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv")
print(df['SLA_Breach_Pct'].describe())
print(df['SLA_Breach_Pct'].mean())

count    948000.000000
mean         84.701477
std          35.997345
min           0.000000
25%         100.000000
50%         100.000000
75%         100.000000
max         100.000000
Name: SLA_Breach_Pct, dtype: float64
84.70147679324894

In [5]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Admin\Desktop\project cv 1\Data\quick_commerce_cleaned.csv")
print(df.columns.tolist())

['Order_ID', 'Company', 'City', 'Customer_Age', 'Order_Value', 'Delivery_Time_Min', 'Distance_Km', 'Items_Count', 'Product_Category', 'Payment_Method', 'Customer_Rating', 'Discount_Applied', 'Delivery_Partner_Rating', 'SLA_Breach', 'Distance_Bucket', 'Above_City_Avg', 'City_Avg_Delivery_Time', 'SLA_Breach_Pct']